"""Single operation catalog shared by CLI and MCP front ends."""

TOOL_SPEC = [
    {"name": "capabilities", "description": "Report device capabilities and identity.", "read_only": True},
    {"name": "snapshot", "description": "Capture a JPEG snapshot; returns bytes/SHA-256.", "read_only": True,
     "params": {"preview_max_width": "int"}},
    {"name": "ocr", "description": "OCR the screen (or a provided image); returns text.", "read_only": True,
     "params": {"image_b64": "str (optional base64 image)"}},
    {"name": "verify", "description": "Verify which machine is on screen.", "read_only": True,
     "params": {"machine": "str", "policy": "none|frame_change|ocr_identity|prompt_pattern"}},
    {"name": "host.identity.inspect", "description": "Inspect configured host identity.", "read_only": True},
    {"name": "host.graphics.inspect", "description": "Inspect configured host graphics and DRM nodes.", "read_only": True},
    {"name": "service.render_access.inspect", "description": "Inspect render service and device access.", "read_only": True},
    {"name": "host.reboot", "description": "Reboot a named host after target-bound confirmation.", "write_gate": True,
     "params": {"target": "str", "confirmation": "str"}},
    {"name": "select", "description": "Switch KVM port to a named machine (held-key recipe).", "write_gate": True,
     "params": {"machine": "str", "verify_policy": "str", "rearm": "bool", "settle_s": "float"}},
    {"name": "hid_reset", "description": "Reset the HID subsystem.", "write_gate": True},
    {"name": "rearm_otg", "description": "OTG gadget bounce to re-arm hotkey engine.", "write_gate": True},
    {"name": "kvm_send_text", "description": "Type mapped text through the selected KVM target.", "write_gate": True},
    {"name": "kvm_send_keys", "description": "Send a validated key shortcut through the selected KVM target.", "write_gate": True},
    {"name": "kvm_hold_key", "description": "Hold one key for a bounded duration, then release it.", "write_gate": True},
    {"name": "kvm_release_all", "description": "Release keys tracked as held by this client.", "write_gate": True},
    {"name": "kvm_mouse_move", "description": "Move the selected target mouse to normalized coordinates.", "write_gate": True},
    {"name": "kvm_mouse_move_pct", "description": "Move the selected target mouse by screen percentage.", "write_gate": True},
    {"name": "kvm_mouse_click", "description": "Click a mouse button on the selected target.", "write_gate": True},
    {"name": "kvm_mouse_scroll", "description": "Scroll the selected target mouse wheel.", "write_gate": True},
    {"name": "kvm_status", "description": "Report KVM authentication and held-key state.", "write_gate": False, "read_only": True},
    {"name": "kvm_screenshot_to_file", "description": "Save a current KVM screenshot to a file.", "write_gate": False, "read_only": True},
    {"name": "kvm_ocr_screenshot", "description": "OCR a screenshot and return text coordinates.", "write_gate": False, "read_only": True},
    {"name": "kvm_ocr_click", "description": "Find OCR text and click its best match.", "write_gate": True},
    {"name": "exec_command", "description": "Run an allowlisted command over SSH; requires explicit SSH transport.",
     "write_gate": True, "params": {"command": "str", "transport": "ssh"}},
    {"name": "kvm_sequence_plan", "description": "Validate and plan a target-bound KVM sequence.", "write_gate": False, "read_only": True},
    {"name": "kvm_sequence_authorize", "description": "Authorize a planned KVM sequence.", "write_gate": True, "read_only": False},
    {"name": "kvm_sequence_execute", "description": "Execute an authorized KVM sequence.", "write_gate": True, "read_only": False},
    {"name": "kvm_workflow_authorize", "description": "Authorize a named KVM workflow.", "write_gate": True, "read_only": False},
    {"name": "kvm_workflow_list", "description": "List named KVM workflows.", "write_gate": False, "read_only": True},
    {"name": "kvm_workflow_inspect", "description": "Inspect a named KVM workflow.", "write_gate": False, "read_only": True},
    {"name": "kvm_workflow_execute", "description": "Execute a named KVM workflow.", "write_gate": True, "read_only": False},
]

OPERATION_NAMES = frozenset(item["name"] for item in TOOL_SPEC)
